### ISSUE TITLE
执行 go run main.go 报错

### ISSUE THREAD

**Issue by jiangtao6888** [mlogclub/mlog#14]
2019/07/29 10:19:55 /Users/knight/Repository/go/pkg/mod/github.com/ikeikeikeike/go-sitemap-generator/v2@v2.0.2/stm/sitemap.go:14: Max processors 8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x16c9bc6]

goroutine 62 [running]:
github.com/ikeikeikeike/go-sitemap-generator/v2/stm.(*Sitemap).XMLContent(...)
        /Users/knight/Repository/go/pkg/mod/github.com/ikeikeikeike/go-sitemap-generator/v2@v2.0.2/stm/sitemap.go:103
github.com/mlogclub/mlog/services.(*articleService).GenerateSitemap(0x22eb0f8)
        /Users/knight/Repository/go/src/mlog/services/article_service.go:294 +0x5c6
github.com/mlogclub/mlog/app.generateSitemapAndRss.func1()
        /Users/knight/Repository/go/src/mlog/app/starting.go:20 +0x2d
created by github.com/mlogclub/mlog/app.generateSitemapAndRss
        /Users/knight/Repository/go/src/mlog/app/starting.go:19 +0x35
exit status 2

**Comment by m-log** [comment]
已经修复。
